### ISSUE TITLE
`__file__` check doesn't work in chdir

### ISSUE THREAD

**Issue by Akuli** [RedFantom/python-tkimg#1]
Currently the build is failing because `load_tkimg()` changes directory and calls `get_pkgindex_path()`, which then calls `get_tkimg_path()` which uses `__file__` which is a relative path. Solution:

```python3
# put this to the top of the file
_ABSOLUTE_PATH = os.path.abspath(__file__)

...

def get_tkimg_path():
    # do something with _ABSOLUTE_PATH
```

I'm not sure if you knew this already. I thought I might as well point it out.

**Comment by RedFantom** [comment]
So, what I did in the master branch was squash together the last seven commits (as they were all for the same purpose), and then the CI suddenly succeeded, even though the path finding was not changed in any of those commits. 

Still, I have implemented your suggestion, thank you so much for it! Even if the CI is passing right now, this makes the library work when actually using it.
